require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'B1Mobile' do
  use_expo_modules!

  # Modular headers only for the Firebase / Google deps that need them
  # (use_modular_headers! globally breaks RN's react_runtime module)
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Bump all pods' iOS deployment target to match the project's
    # (YouVersionReactNative requires iOS 17.0 minimum)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
    end

    # Fix Stripe STPPaymentStatus enum type mismatch with Xcode 26+
    # NSUInteger vs NSInteger in StripeSwiftInterop.h forward declaration
    stripe_interop = File.join(installer.sandbox.root, '..', '..', 'node_modules', '@stripe', 'stripe-react-native', 'ios', 'StripeSwiftInterop.h')
    if File.exist?(stripe_interop)
      content = File.read(stripe_interop)
      if content.include?('NS_ENUM(NSUInteger, STPPaymentStatus)')
        content.gsub!('NS_ENUM(NSUInteger, STPPaymentStatus)', 'NS_ENUM(NSInteger, STPPaymentStatus)')
        File.write(stripe_interop, content)
      end
    end

    # Fix fmt consteval build error with Xcode 26+ / newer clang
    # Patch fmt/base.h to disable consteval for all Apple clang versions
    fmt_base = File.join(installer.sandbox.root, 'fmt/include/fmt/base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('consteval is broken in Apple clang / Xcode 26+')
        content.gsub!(
          '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L' + "\n" +
          '#  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang < 14.',
          '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L' + "\n" +
          '#  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang < 14.' + "\n" +
          '#elif defined(__apple_build_version__)' + "\n" +
          '#  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang / Xcode 26+.'
        )
        File.write(fmt_base, content)
      end
    end
  end
end
